### ISSUE TITLE
JupyterLab 4 Support?

### ISSUE THREAD

**Issue by MRYingLEE** [jupyterlab-contrib/jlab-enhanced-cell-toolbar#67]
I wish this extension will support JupyterLab 4.

**Comment by fcollonval** [comment]
Hey @MRYingLEE all extensions will likely be updated to Lab 4 when the final version is out.

**Comment by MRYingLEE** [comment]
I succeeded testing a few functions of this extension in Jupyterlab 4.  It is wonderful. 
But I am still waiting for an official upgrade.

**Comment by virgilus** [comment]
Hey! It'd be amazing if this extension could work in jupyterlab 4. Being able to visualize the cell tag names for each cell was very useful. Thank you and good luck! :)

**Comment by mengyanw** [comment]
Hi, I would like to work on adding Jupyterlab 4 support to the extension and will try to make a pull request this week :)

**Comment by yimmasyimmas** [comment]
We appreciate your great work. Thanks a lot for the extension. Since we upgraded to Jupyterlab 4 we are not able to use your awesome extension :( .Could you please release the version which supports Jupyterlab 4? We were using your extension extensively.

**Comment by yimmasyimmas** [comment]
> We appreciate your great work. Thanks a lot for the extension. Since we upgraded to Jupyterlab 4 we are not able to use your awesome extension :( .Could you please release the version which supports Jupyterlab 4? We were using your extension extensively.

I also tried to migrate to Jupyter 4 via script : python -m jupyterlab.upgrade_extension . ıt successfully created necessary files.

But when i try to install from the upgraded files via : python -m pip install t:\PYTHON\Lib\site-packages\jlab_enhanced_cell_toolbar\labextension  command , it gave an error with : 

"
 INFO:hatch_jupyter_builder.utils:> C:\Users\060580\AppData\Local\Temp\pip-build-env-hjkb9q1h\overlay\Scripts\jlpm.EXE run build:prod
      Building extension in .
      [
        {
          instancePath: '',
          schemaPath: '#/additionalProperties',
          keyword: 'additionalProperties',
          params: { additionalProperty: '_build' },
          message: 'must NOT have additional properties'
        }
      ]
      C:\Users\060580\AppData\Local\Temp\pip-build-env-hjkb9q1h\overlay\Lib\site-packages\jupyterlab\debuglog.py:56: UserWarning: An error occurred.
        warnings.warn("An error occurred.")
      C:\Users\060580\AppData\Local\Temp\pip-build-env-hjkb9q1h\overlay\Lib\site-packages\jupyterlab\debuglog.py:57: UserWarning: subprocess.CalledProcessError: Command '['node', 'T:\\PYTHON\\Lib\\site-packages\\jlab_enhanced_cell_toolbar\\labextension\\node_modules\\@jupyterlab\\builder\\lib\\build-labextension.js', '--core-path', 'C:\\Users\\060580\\AppData\\Local\\Temp\\pip-build-env-hjkb9q1h\\overlay\\Lib\\site-packages\\jupyterlab\\staging', 'T:\\PYTHON\\Lib\\site-packages\\jlab_enhanced_cell_toolbar\\labextension']' returned non-zero exit status 1.
        warnings.warn(msg[-1].strip())
      C:\Users\060580\AppData\Local\Temp\pip-build-env-hjkb9q1h\overlay\Lib\site-packages\jupyterlab\debuglog.py:58: UserWarning: See the log file for details: C:\Users\060580\AppData\Local\Temp\jupyterlab-debug-d1srtma2.log
        warnings.warn(f"See the log file for details: {log_path!s}")
      Traceback (most recent call last):
        File "T:\PYTHON\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "T:\PYTHON\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "T:\PYTHON\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\060580\AppData\Local\Temp\pip-build-env-hjkb9q1h\overlay\Lib\site-packages\hatchling\build.py", line 56, in build_wheel
          return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
        File "C:\Users\060580\AppData\Local\Temp\pip-build-env-hjkb9q1h\overlay\Lib\site-packages\hatchling\builders\plugin\interface.py", line 150, in build
          build_hook.initialize(version, build_data)
        File "C:\Users\060580\AppData\Local\Temp\pip-build-env-hjkb9q1h\normal\Lib\site-packages\hatch_jupyter_builder\plugin.py", line 87, in initialize
          raise e
        File "C:\Users\060580\AppData\Local\Temp\pip-build-env-hjkb9q1h\normal\Lib\site-packages\hatch_jupyter_builder\plugin.py", line 82, in initialize
          build_func(self.target_name, version, **build_kwargs)
        File "C:\Users\060580\AppData\Local\Temp\pip-build-env-hjkb9q1h\normal\Lib\site-packages\hatch_jupyter_builder\utils.py", line 115, in npm_builder
          run([*npm_cmd, "run", build_cmd], cwd=str(abs_path))
        File "C:\Users\060580\AppData\Local\Temp\pip-build-env-hjkb9q1h\normal\Lib\site-packages\hatch_jupyter_builder\utils.py", line 229, in run
          return subprocess.check_call(cmd, **kwargs)
        File "T:\PYTHON\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\060580\\AppData\\Local\\Temp\\pip-build-env-hjkb9q1h\\overlay\\Scripts\\jlpm.EXE', 'run', 'build:prod']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.  

"

So your help on upgrading to Jupyterlab4 is  appreciated.

**Comment by yimmasyimmas** [comment]
is this project dead?

**Comment by JasonWeill** [comment]
@yimmasyimmas We'd be happy to consider a pull request to add Lab 4 support; please let us know if you have questions about submitting one.

**Comment by yimmasyimmas** [comment]
> @yimmasyimmas We'd be happy to consider a pull request to add Lab 4 support; please let us know if you have questions about submitting one.

@JasonWeill  thank you very much for your response. We would be very glad to see the jupyterlab4 support. This is why i cant update from jupyterlab 3  and use the great benefits of jupyterlab 4. Do I need to take any action for the pull request?  ( I  dont have enough experience doing that, but if necessary i can do my best to do that)öOr you will handle it?

Thank you very much again.

**Comment by JasonWeill** [comment]
@yimmasyimmas This is an open source project, run largely by volunteers who have other priorities as well. We welcome pull requests from contributors who can help upgrade this extension to support Lab 4.

**Comment by jonnyhtw** [comment]
+1 for adding v4 support if possible. I would volunteer to help but this would be vastly above my abilities. I've downgraded to v3 and it works wonderfully. 

cheers 😄

**Comment by fabrizziosoares** [comment]
I''d like to contribute, but I even know how to start debuging this kind project. If somebody can give some directions, I can try to help.
